version: '3'

services:
 otel-collector:
   image: otel/opentelemetry-collector-contrib:0.120.0
   ports:
     - "4317:4317"  # OTLP gRPC
     - "4318:4318"  # OTLP HTTP
     - "55679:55679"  # Prometheus metrics (optional)
   environment:
     - OTEL_LOG_LEVEL=DEBUG

 swarm_node:
   image: europe-docker.pkg.dev/gensyn-public-b7d9/public/rl-swarm:v0.0.1
   command: ./run_hivemind_docker.sh
   environment:
     - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
     - PEER_MULTI_ADDRS=/ip4/38.101.215.13/tcp/30002/p2p/QmQ2gEXoPJg6iMBSUFWGzAabS2VhnzuS782Y637hGjfsRJ
     - HOST_MULTI_ADDRS=/ip4/0.0.0.0/tcp/38331
   ports:
     - "38331:38331"  # Exposes the swarm node's P2P port
   depends_on:
     - otel-collector

 fastapi:
    build:
      context: .
      dockerfile: Dockerfile.webserver
    environment:
      - OTEL_SERVICE_NAME=rlswarm-fastapi
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - INITIAL_PEERS=/ip4/38.101.215.13/tcp/30002/p2p/QmQ2gEXoPJg6iMBSUFWGzAabS2VhnzuS782Y637hGjfsRJ
    ports:
      - "8080:8000"
    depends_on:
      - otel-collector
      - swarm_node
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/healthz"]
      interval: 30s
      retries: 3
